### ISSUE TITLE
The truth

### ISSUE THREAD

**Issue by ghost** [grufkork/DownOnSpot#2]
Ever since spotify did the credentials change thing, down on spot has never worked for me, I have tried all the workarounds and librespot authenticator etc etc, it just hasn't worked once. How many months has it been since this program actually worked or am I doing something wrong. To my knowledge, email/password login is completely removed and replaced with oauth, but why hasn't librespot/downonspot added some kind of oauth flow? the config is still username and password which surely would never work since its removed? idk

**Comment by oSumAtrIX** [comment]
librespot authenticator is working on the latest commit I pushed originally

**Comment by munzembaesdras** [comment]
how can i connect the librespot with the downonspot ? i read doc but see nothing to  help me

**Comment by ghost** [comment]
> Same here, getting an authentication error.



> how can i connect the librespot with the downonspot ? i read doc but see nothing to help me

I recommend using a playlist converter like tunemymusic to convert spotify playlists to deezer, then use deemix to download the songs, you can also download FLAC lossless versions of the files as a bonus. 

If you don't care about quality, there are tons of spotify downloaders out there that will do a similar thing by finding the matching youtube video to the spotify song then downloading that like spotdl etc.
